# Generated by Django 4.0.4 on 2022-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biseccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xi', models.FloatField()),
                ('Xs', models.FloatField()),
                ('Tol', models.FloatField()),
                ('Niter', models.FloatField()),
                ('funcion', models.CharField(max_length=50)),
            ],
        ),
    ]
